branches:
  only:
    - master

services:
  - docker

before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

before_script:
  - repo=fingershock/bitgo-express
  - git_rev=$(git rev-parse --short HEAD)
  - build_date=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

script:
  - docker build -t $repo --build-arg VCS_REF=$git_rev --build-arg BUILD_DATE=$build_date .
  - docker run --rm $repo /usr/local/lib/node_modules/bitgo/bin/bitgo-express --version

after_success:
  - tag=$(docker run --rm $repo --entrypoint=/bin/sh -c 'echo $BITGO_VERSION')
  - docker tag $repo $repo:$tag
  - docker push $repo:latest
  - docker push $repo:$tag

notifications:
  slack:
    secure: JN6PcNERgpgI1wKZxMN9cMWarZG4Skc+l2oknVkmnelYEopSCsecGOxhD7cuu1PL1DlMbm+0hqGb194Fd+hUuPfrBP3UFDgaaHF5DrddrxrRZ19xfDk0mPnJh5rC4Kv6QOGtP5R/djUhCkFMmFyj9wUytyLBhG/GcnXbOuuGifN5XIuIB1AWlKLyRdANaZeVV3wKnuLYOGBDBckxYzGFypJ9jqpEO465HOqUgOG1qNt++cc/3Yq7HNKOgzey0uaS54fK0TsM2crJMixBLjtbARJ9RhqukyntV7UpzfEk23CfW4JsfrE3iHPqnWbHW6wiivd3iv3TCT9LnplY+ddp+valh9ALFIbh49zS02V8TAh2xQnVGBVYC+RPlOyxiDbGbXEiqx+iD1Lqn5rfC7nzVDkiMezzfLAPT4A2pmxQO6kIQWkHRN+gkCYM3Tt7Mj1ngfW5a6yOOxCm7FrhQw6RZispcQ4Ud1/wbLeUCwKBdajrFCp2Um8lnrdx4vbqhWhyRNZ/WQbIaj2zsqA+aeC2TTPxkFnHI6VUjLGDE9FaBTQjYge7Wi/FdLRy7NqUbciLlcV45/2A8VhksXqQX5oo8OyqiutA9EQoltA5pPCfDP6OuTVVh3CGPSudn/4zygy4KUp6VJToTcd5tBBWR16th68JUC0T8o0io+QBa0zRFes=
